version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chips
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DATABASE_URL: postgres://user:pass@db:5432/chips
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  db-data: