# 使用する Node.js イメージ
FROM node:18-alpine AS base

# 作業ディレクトリを設定
WORKDIR /usr/src/app

# パッケージ定義ファイルをコピーして依存をインストール
COPY package*.json ./
RUN npm ci

# ソースコードをコピー
COPY . .

# 本番環境用の設定
FROM base AS release
ENV NODE_ENV=production
EXPOSE 3000
CMD ["node", "src/server.js"]