# .github/workflows/ci.yml
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: casino_chip_db
        ports: ['5432:5432']
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd backend
          npm ci
      - name: Run migrations
        run: npm run migrate:up
      - name: Run tests
        run: npm test